### ISSUE TITLE
PHP AGENT Exception: eval() parse error: syntax error in Handler->do_invoke() and Handler->handle()

### ISSUE THREAD

**Issue by Th3FirstAvenger** [kraken-ng/Kraken#6]
## Description
I encountered an error while using Kraken with Python 3.8 on Kali WSL. When running Kraken with the default agent, I encountered the following error:

```php
Exception: eval() parse error: syntax error, unexpected end of file in /var/www/xxx/templates/cassiopeia/html/mod_articles_archive/default.php:255
Stack trace:
#0 /var/www/xxxx/templates/cassiopeia/html/mod_articles_archive/default.php(300): Handler->do_invoke()
#1 /var/www/xxxx/templates/cassiopeia/html/mod_articles_archive/default.php(326): Handler->handle()
#2 {main}
```
![image](https://github.com/kraken-ng/Kraken/assets/67591596/17552d40-21e3-47ef-a9be-11d89af43037)

This error seems to be related to the PHP st agent. I am using Python 3.8 on Kali WSL, and I ran into this problem when using the default Kraken agent.

Please let me know if there are any additional details or logs you need to investigate this problem further.

## Environment
- Operating System: Kali Linux (WSL)
- Python Version: 3.8
- Kraken Version: 1.2.0

**Comment by Th3FirstAvenger** [comment]
The issue has been resolved by using the tool located in `utils/fix_symbolic_link` with the command, `python3 fix_symbolic_links.py --modules-path ../../modules`.
Therefore, I am closing this issue. Thank you!
